//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuParser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MenuParser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;Global Eats Group&quot;,
        ///  &quot;Restaurants&quot;: [
        ///    {
        ///      &quot;Name&quot;: &quot;Downtown Diner&quot;,
        ///      &quot;Location&quot;: &quot;Seattle, WA&quot;,
        ///      &quot;Menus&quot;: [
        ///        {
        ///          &quot;Name&quot;: &quot;Breakfast&quot;,
        ///          &quot;Categories&quot;: [
        ///            {
        ///              &quot;Name&quot;: &quot;Pancakes &amp; Waffles&quot;,
        ///              &quot;MenuItems&quot;: [
        ///                {
        ///                  &quot;Name&quot;: &quot;Buttermilk Pancakes&quot;,
        ///                  &quot;Description&quot;: &quot;Fluffy pancakes served with maple syrup.&quot;,
        ///                  &quot;BasePrice&quot;: 7.99,
        ///                  &quot;M [rest of string was truncated]&quot;;.
        /// </summary>
        public static string JsonData {
            get {
                return ResourceManager.GetString("JsonData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name,Description,BasePrice
        ///Buttermilk Pancakes,Fluffy pancakes with maple syrup,7.99
        ///Belgian Waffle,Crispy waffle with whipped cream,8.49
        ///Coffee,Freshly brewed hot coffee,2.5
        ///Orange Juice,Fresh squeezed orange juice,3.25.
        /// </summary>
        public static string MenuItem_txt {
            get {
                return ResourceManager.GetString("MenuItem.txt", resourceCulture);
            }
        }
    }
}
